server_connect_timeout: 5000
remote_ping_cache: -1
forge_support: false
player_limit: 200
permissions:
  default:
  admin:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.reload
timeout: 30000
log_commands: true
network_compression_threshold: 256
online_mode: true
disabled_commands:
servers:
  example:
    motd: '&6New Server'
    address: localhost:25577
    restricted: false
listeners:
- query_port: 25565
  motd: '&6Neuer Bungeecord Server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
  ping_passthrough: false
  priorities:
  - example
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 200
  tab_size: 60
  force_default_server: false
ip_forward: true
remote_ping_timeout: 5000
prevent_proxy_connections: true
groups:
connection_throttle: 8000
connection_throttle_limit: 5
log_pings: true